apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wgdod14jn-nodejs 
  janus-idp.io/tekton: wgdod14jn-nodejs
  backstage.io/kubernetes-id: wgdod14jn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgdod14jn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml